name: build
permissions:
  contents: write

# execute this workflow automatically, but only when pushing to master
on:
  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Update README.md file
      shell: bash
      run: |

        # first generate the lemmy-stats-crawler.json file
        ./stats-crawler.sh

        # process the json file and update the README.md file
        ./generate_readme.py

        # push new README to GitHub
        git config --global user.name 'maltfield'
        git config --global user.email 'michael@michaelaltfield.net'
        git add -f awesome-lemmy-instances.csv
        git add -f README.md
        git commit -am "Auto-update"
        git push

